### ISSUE TITLE
mnFullpage options not being applied to ngFor iterations

### ISSUE THREAD

**Issue by mafav** [meiblorn/ngx-fullpage#180]
Hi @meiblorn 

If I use an ngFor loop and wrap it around the sections, the mnFullpage options aren't being applied.

Any remedy for this? I think it would be a good feature for large reports etc.

![ngfor_sections](https://cloud.githubusercontent.com/assets/18747081/21536147/7dc08566-cdca-11e6-8a63-d4ab7ca44ee6.png)

**Comment by hrangel** [comment]
Up to that.
I've a workaround for the sections to work:
```typescript
ngAfterViewInit() {
    this.fullpageService.reBuild();
    this.fullpageService.silentMoveTo(1);
  }
```

But the navigation won't work, I've to build the navigation list manually

**Comment by enviermon** [comment]
Hi,
my workaround:

**dont** install: npm install ng2-fullpage --save      //  but 
1. npm install @types/jquery --save-dev
  npm install fullpage.js
2. create a folder fullpagetest in app with:
- mnFullpage-options.class.ts	
- mnFullpage.directive.ts	
- mnFullpage.module.ts	Release 2.1.0	
- mnFullpage.service.ts
3. in AppComponent 
- import {MnFullpageDirective} from "./fullpagetest/mnFullpage.directive";
- implements AfterViewInit
`@ViewChild(MnFullpageDirective) vc:MnFullpageDirective;
 ngAfterViewInit(): void {
    this.vc.callme();
  }`
4. in mnFullpage.directive.ts
- delete code in ngOnInit
`/**
         * Enable fullpage for the element
         */
        //(<any>$)(this._el.nativeElement).fullpage(this.options);
`
- create func:
` callme() {
        (<any>$)(this._el.nativeElement).fullpage(this.options);
    }`

**Comment by enviermon** [comment]
app.component.html:
`<div mnFullpage
     [mnFullpageNavigation]="true"
     [mnFullpageKeyboardScrolling]="true"
     [mnFullpageSlidesNavigation]="true"
     [mnFullpageControlArrows]="true">`
`<div *ngFor="let item of items" class="section">Some section</div> </div>`

**Comment by meiblorn** [comment]
Updated to the new version. Closing.
