### ISSUE TITLE
AOT compliant support

### ISSUE THREAD

**Issue by moioo91120** [meiblorn/ngx-fullpage#195]
Hello,

I love your library, however with aot build, I get the following error : 

ERROR in Unexpected value 'MnFullpageDirective in  node_modules/ng2-fullpage/components/fullpage/mnFullpage.directive.d.ts' imported by the module 'HomepageModule in src/app/homepage/homepage.module.ts'
 
It seems that your project is missing the .metadata.json file (https://github.com/angular/angular/issues/11262)

**Comment by meiblorn** [comment]
Hi, @moioo91120 !

Thank you for your kind words. 
I have no a enough free time now, so if you want you are free to create poll request with the necessary changes. I'll review and push it asap.

Thanks for interest!

**Comment by moioo91120** [comment]
Ok I'll see what I can do

**Comment by moioo91120** [comment]
Ok, here is what i found :  

Basically, you can use "ngc" to build aot compliant library :  

1) npm install --save-dev @angular/compiler-cli typescript@2 @angular/platform-server @angular/compiler
2)  add to tsconfig.json : ,
  "angularCompilerOptions": {
	"strictMetadataEmit": true,
	"genDir": "./build",
	"debug": true
  }
3) change in package.json to     "build:prod": "concurrently \"webpack --config ./config/webpack/webpack.prod.babel.js  --progress --profile --colors --display-error-details --display-cached --bail\" \"ngc -p ./tsconfig.json\" ",
4) fix 1/2 things in the library to adapt for aot .

I got it working with the following diff (it pass your karma test as well), I'm not really familiar with GIT and it seems that I don't have the necessary permission to create a branch + pull request with changes. So here is the diff
[Uploading diff_to_add_aot.txt…]()


The result looks good, we have metadata and everything and it's still working with JIT application
HOWEVER, it still break with AOT application ...

The error is relative to a "makeDecorator" function that is not correctly exported. It seems that the library is missing something to be compiled with aot correctly  (https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.iqsud3754 )

Any idea what this error can be related to ?

**Comment by moioo91120** [comment]
Ok, here is what i found :  

Basically, you can use "ngc" to build aot compliant library :  

1) npm install --save-dev @angular/compiler-cli typescript@2 @angular/platform-server @angular/compiler
2)  add to tsconfig.json : ,
  "angularCompilerOptions": {
	"strictMetadataEmit": true,
	"genDir": "./build",
	"debug": true
  }
3) change in package.json to     "build:prod": "concurrently \"webpack --config ./config/webpack/webpack.prod.babel.js  --progress --profile --colors --display-error-details --display-cached --bail\" \"ngc -p ./tsconfig.json\" ",
4) fix 1/2 things in the library to adapt for aot .

I got it working with the following diff (it pass your karma test as well), I'm not really familiar with GIT and it seems that I don't have the necessary permission to create a branch + pull request with changes. So here is the diff
[Uploading diff_to_add_aot.txt…]()


The result looks good, we have metadata and everything and it's still working with JIT application
HOWEVER, it still break with AOT application ...

The error is relative to a "makeDecorator" function that is not correctly exported. It seems that the library is missing something to be compiled with aot correctly  (https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.iqsud3754 )

Any idea what this error can be related to ?

**Comment by moioo91120** [comment]
diff --git a/.gitignore b/.gitignore
index 9196935..294a0eb 100644
--- a/.gitignore
+++ b/.gitignore
@@ -52,3 +52,6 @@ node_modules
 
 # Optional REPL history
 .node_repl_history
+
+# Compiled aot
+*.metadata.json
diff --git a/components/fullpage/mnFullpage.directive.ts b/components/fullpage/mnFullpage.directive.ts
index f13ba19..0ef49e3 100644
--- a/components/fullpage/mnFullpage.directive.ts
+++ b/components/fullpage/mnFullpage.directive.ts
@@ -9,10 +9,10 @@ import 'fullpage.js';
 
 import {MnFullpageOptions} from './mnFullpage-options.class';
 
-const DIRECTIVE_NAME = 'mnFullpage';
+// const DIRECTIVE_NAME = 'mnFullpage';
 
 @Directive({
-    selector: `[${DIRECTIVE_NAME}]`
+    selector: `[mnFullpage]`
 })
 export class MnFullpageDirective implements OnInit {
 
@@ -21,12 +21,12 @@ export class MnFullpageDirective implements OnInit {
      *
      * @type {string} prefix
      */
-    private static propertyPrefix: string = `${DIRECTIVE_NAME}`;
+    private static propertyPrefix: string = `mnFullpage`;
 
     /**
      * Directive options reference
      */
-    @Input(`${DIRECTIVE_NAME}`) public options: MnFullpageOptions;
+    @Input(`mnFullpage`) public options: MnFullpageOptions;
 
diff --git a/package.json b/package.json
index cde23e0..3985345 100644
--- a/package.json
+++ b/package.json
@@ -23,18 +23,20 @@
   },
   "main": "ng2-fullpage.js",
   "dependencies": {
-    "@angular/common": "2.4.1",
-    "@angular/compiler": "2.4.1",
-    "@angular/core": "2.4.1",
+    "@angular/common": "2.4.3",
+    "@angular/compiler": "2.4.3",
+    "@angular/core": "2.4.3",
     "jquery": "^3.1.1",
     "fullpage.js": "^2.9.2"
   },
   "devDependencies": {
-    "@angular/forms": "^2.4.1",
-    "@angular/http": "2.4.1",
-    "@angular/platform-browser": "2.4.1",
-    "@angular/platform-browser-dynamic": "2.4.1",
-    "@angular/platform-server": "2.4.1",
+    "@angular/compiler": "^2.4.3",
+    "@angular/compiler-cli": "^2.4.3",
+    "@angular/forms": "^2.4.3",
+    "@angular/http": "2.4.3",
+    "@angular/platform-browser": "2.4.3",
+    "@angular/platform-browser-dynamic": "2.4.3",
+    "@angular/platform-server": "^2.4.3",
     "@types/core-js": "^0.9.35",
     "@types/hammerjs": "^2.0.34",
     "@types/jasmine": "^2.5.38",
@@ -104,7 +106,7 @@
     "tslint": "4.2.0",
     "tslint-loader": "^3.3.0",
     "typedoc": "^0.5.1",
-    "typescript": "2.1.4",
+    "typescript": "^2.1.5",
     "typings": "^2.1.0",
     "unminified-webpack-plugin": "^1.2.0",
     "url-loader": "^0.5.7",
@@ -136,8 +138,8 @@
     "ncu": "ncu -a",
     "webpack-dev-server": "webpack-dev-server",
     "build": "npm run build:dev",
-    "build:dev": "concurrently \"webpack --config ./config/webpack/webpack.dev.babel.js --progress --profile --colors --display-error-details --display-cached\" && tsc",
-    "build:prod": "concurrently \"webpack --config ./config/webpack/webpack.prod.babel.js  --progress --profile --colors --display-error-details --display-cached --bail\" \"tsc\"",
+    "build:dev": "concurrently \"webpack --config ./config/webpack/webpack.dev.babel.js --progress --profile --colors --display-error-details --display-cached\" && ngc -p ./tsconfig.json",
+    "build:prod": "concurrently \"webpack --config ./config/webpack/webpack.prod.babel.js  --progress --profile --colors --display-error-details --display-cached --bail\" \"ngc -p ./tsconfig.json\" ",
     "server": "npm run server:dev",
     "server:dev": "DASHBOARD=true webpack-dashboard -- webpack-dev-server --config config/webpack/webpack.dev.babel.js --progress --profile --watch --content-base demo/",
     "server:prod": "DASHBOARD=true webpack-dashboard -- npm run build:prod && http-server build --cors",
diff --git a/tsconfig.json b/tsconfig.json
index 9e68b4c..91d45e8 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -44,5 +44,10 @@
   "buildOnSave": false,
   "atom": {
     "rewriteTsconfig": false
+  },
+  "angularCompilerOptions": {
+	"strictMetadataEmit": true,
+	"genDir": "./build",
+	"debug": true
   }
 }

**Comment by etouraille** [comment]
I created a pull request to enable aot compiling following this tutorila : https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.76h9rexij

**Comment by meiblorn** [comment]
Updated to the new version. Closing.
