### ISSUE TITLE
Doesn't working on angular-cli latest version above 1.0.3

### ISSUE THREAD

**Issue by smartHasmukh** [meiblorn/ngx-fullpage#411]
Displayed error on console.

`compiler.es5.js:1540Uncaught Error: Unexpected value 'MnFullpageDirective' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.(…)`

![error](https://cloud.githubusercontent.com/assets/8941195/26519898/06d83a5c-42e6-11e7-96e4-40fd748e889d.png)

**Comment by tiancovici** [comment]
Can you show your app.module.ts (or wherever you have NgModule
Also can you show .angular-cli.json file?

**Comment by meiblorn** [comment]
Outdated
