### ISSUE TITLE
Problem when run npm run build 

### ISSUE THREAD

**Issue by ealexisaraujo** [meiblorn/ngx-fullpage#440]
![image](https://user-images.githubusercontent.com/9372769/27444003-7e2bbf1c-573a-11e7-9c82-93de95f3ef44.png)

**Comment by shwetapurushe** [comment]
Has anyone been able to build this git project. 'npm run build', 'npm start' and 'ng serve' dont seem to be working. Am i missing something?
Any help is appreciated.

**Comment by meiblorn** [comment]
npm install

then

npm start
npm run build
