### ISSUE TITLE
Fullpage.js can only be initialized once and you are doing it multiple times!

### ISSUE THREAD

**Issue by seanmavley** [meiblorn/ngx-fullpage#451]
This happens with simple back and forth of the routes using the browser navigation.

For example, steps:

- go to homapge of your app, say /home
- click to go to fullpage.js enabled component, say /withfullpage
- click your browser back button, should go to /home
- then click forward which should go to /withfullpage

The error is: `fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!` and the page is broken with regards to it being fullpage enabled.

**Comment by skbelalmd** [comment]
Add this code to your component
 ngOnDestroy() { this.fullpageService.destroy('all'); }

**Comment by seanmavley** [comment]
Thanks. Using swipejs now though.

**Comment by besserwisser** [comment]
@seanmavley can you post your approach of replacing fullpage.js with swipejs?

**Comment by seanmavley** [comment]
@besserwisser I'm using this project for my swiperjs https://github.com/zefoy/ngx-swiper-wrapper
