### ISSUE TITLE
Problems with ASP.NET Core / Angular 4 stack (possible due to AppState error)

### ISSUE THREAD

**Issue by IlyaSolovyov** [meiblorn/ngx-fullpage#454]
I have created an Angular 4 / ASP.NET Core application using VS2017's built-in example application. I wanted to add fullpage.js support using your directive and followed the webpack installation guide. Alas, the result is just my divs displayed like they would display without fullpage.js, i.e. one after another without any fullpage-mechanics. 
![default](https://user-images.githubusercontent.com/23297756/33230131-968535da-d1e6-11e7-8209-45d076b3cd6a.png)

The instructions were followed correctly, except for the "AppState" removed, because TS could not detect what it is.  Server pre-rendering has been disabled, and there are no errors anywhere. Is there any way to fix this or should I try to implement fullpage.js without this directive?

**Comment by meiblorn** [comment]
Unable to reproduce
