### ISSUE TITLE
Demo doesen't work?

### ISSUE THREAD

**Issue by ChristopherDicke** [meiblorn/ngx-fullpage#456]
C:\Users\user\scl\scl>ng serve --aot

....

ERROR in Error: Unexpected value 'MnFullpageDirective in C:/Users/user/scl/scl/node_modules/ng2-fullpage/components/fullpage/mnFullpage.directive.d.ts' declared by the module 'AppModule in C:/Users/user/scl/scl/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

`import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";

import { AppComponent } from "./app.component";
import { MnFullpageDirective, MnFullpageService } from "ng2-fullpage";

@NgModule({
    bootstrap: [ AppComponent ],
    declarations: [
        AppComponent,
        MnFullpageDirective // add MnFullpageDirective declaration here
    ],
    imports: [
        BrowserModule,
    ],
    providers: [
        MnFullpageService // also add MnFullpageService provider here
    ]
})
export class AppModule {

}`

Followed this: https://www.npmjs.com/package/ng2-fullpage
Did I do anything wrong or is this not working ?

**Comment by meiblorn** [comment]
Demo works like a charm
