### ISSUE TITLE
Disable fullpage on mobile devices?

### ISSUE THREAD

**Issue by nguyenvannghi** [meiblorn/ngx-fullpage#459]

**Comment by noashka** [comment]
Hello! I solved this issue with using MnFullpageServiceand lifecycle hook AfterViewInit in MyComponent.

```
MyComponent implements AfterViewInit {
  constructor(private fullpageService: MnFullpageService) {}

  ngAfterViewInit() {
    this.fullpageService.destroy('all');
  }
}
```
In ngOnInit hook destroy method isn't working and getting error `ERROR TypeError: $.fn.fullpage.destroy is not a function` because on ngOnInit FullpageComponent is not yet initialized
