### ISSUE TITLE
Not working if the view has childs

### ISSUE THREAD

**Issue by millerf** [meiblorn/ngx-fullpage#461]
Hi,

I tried using your wrapper on this kind of templates:

```
<div id="content-wrapper" [mnFullpage]="options">

  <div *ngFor="let section of dataService.sections" class="section">

    <div *ngFor="let subsection of section.subsections" class="slide">
      <h1>{{subsection.title}}</h1>
    </div>
  </div>
</div>

```

And it wouldn't work. I realized you are calling [here](https://github.com/meiblorn/ngx-fullpage/blob/master/sources/components/fullpage/mnFullpage.directive.ts#L204):
`(<any>$)(this._el.nativeElement).fullpage(this.options);` 
on `ngOnInit()`, but I think it should be on `ngAfterViewInit()`.

I'll push a fix if you find it useful...

**Comment by meiblorn** [comment]
That was fixed in 5.0.2 release. Checkout it.
