### ISSUE TITLE
How do you reinitialize after destroy in Angular 2?

### ISSUE THREAD

**Issue by grubitania** [meiblorn/ngx-fullpage#465]
I have a specific case where half of the page should be FullPage scrollable, and half not. I have an event that   is in charge of that. After I call this.fullPageService.destroy(''), how do I reinitialize this plugin from the components class. In all examples I see the jQuery method $("#id").fullPage();

reBuild method isn't working. 

Any help would be appreciated, thank you!

**Comment by barneythecoder** [comment]
Just set this.fpService.setAutoScrolling to false
