### ISSUE TITLE
Is it planned to add continuousHorizontal option?

### ISSUE THREAD

**Issue by MaksKulykov** [meiblorn/ngx-fullpage#467]
like this:
continuousHorizontal: (default false) Extension of fullpage.js. Defines whether sliding right in the last slide should slide right to the first one or not, and if scrolling left in the first slide should slide left to the last one or not. Not compatible with loopHorizontal. Requires fullpage.js >= 2.8.3.

**Comment by meiblorn** [comment]
Added in 5.0.2
