### ISSUE TITLE
How to set licenseKey?

### ISSUE THREAD

**Issue by zerox12311** [meiblorn/ngx-fullpage#468]
I use this libray , and following document to run my app
I got ***Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option*** message
How to set licenseKey???
thanks!!!

**Comment by andreischwan** [comment]
Add bold line to your .angular-cli.json/angular.json file:

```
      "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/fullpage.js/dist/fullpage.min.js",
              **"node_modules/fullpage.js/LICENSE"**
      ],

```

**Comment by zerox12311** [comment]
I got it.
Thank you!!

**Comment by uxsniper** [comment]
Hi, just purchased a developer key, unfortunately I am receiving the following errors:

fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option.

I tried putting the key inside the LICENSE file but still not working. Where should I initialize the key?

**Comment by meiblorn** [comment]
Fixed

**Comment by meiblorn** [comment]
Fixed: https://github.com/meiblorn/ngx-fullpage/blob/master/sources/components/fullpage/mnFullpage.directive.ts#L40
