### ISSUE TITLE
$ not defined angular6

### ISSUE THREAD

**Issue by seshasui** [meiblorn/ngx-fullpage#471]
$ not defined angular6

**Comment by beshad** [comment]
isn't this compatible with ng6?

**Comment by esolutionsnig** [comment]
Any solution?

**Comment by PuriaRad** [comment]
Any solution?

**Comment by GlebBigma** [comment]
Any solution? :(

**Comment by Ghurka** [comment]
Looks like we need to implement another library that work with angular6

**Comment by benoitcaldei** [comment]
Same problem here..

**Comment by meiblorn** [comment]
Check out scaffolding project https://github.com/meiblorn/ngx-fullpage-scaffolding
This problem should be fixed there
