### ISSUE TITLE
Unable to integrate with Angular 6

### ISSUE THREAD

**Issue by nskshared** [meiblorn/ngx-fullpage#473]
Am trying to integrate fullpage into our angular application. Followed this link https://github.com/meiblorn/ngx-fullpage/wiki/Usage:-Angular-CLI-(Recommended)  but couldn't actually make it work as shown in the demo

Pl can you advise if above link is up-to-date or am I missing something there.

**Comment by emmanuel-cbqa** [comment]
@nskshared Hi buddy, did you find how to use this in angular 6?

**Comment by meiblorn** [comment]
Updated to Angular 7
