### ISSUE TITLE
Module not found: Error: Can't resolve '@fullpage/mnFullpage-options.class'

### ISSUE THREAD

**Issue by jrvaroni** [meiblorn/ngx-fullpage#476]
I installed the new version in my angular project and am having the following error

ERROR in ./node_modules/ngx-fullpage/components/fullpage/mnFullpage.module.js
Module not found: Error: Can't resolve '@fullpage/mnFullpage-options.class' in 'C:\Users\SAMSUNG\Desktop\project\node_modules\ngx-fullpage\components\fullpage'

**Comment by meiblorn** [comment]
Hi, thanks for the reporting.
I've found where is the problem. It will be fixed in few hours.

**Comment by meiblorn** [comment]
Lib is updated. Checkout new version 5.0.2
